sonar.organization=volsch
sonar.projectKey=volsch_md24de-mcp
sonar.projectName=md24de-mcp

sonar.sources=src
sonar.tests=tests
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml
